from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^(?P<prev_id>[-1-9]+)/(?P<article_sub_id>[0-9]+)/(?P<worker_id>[0-9]+)/sieve1/$', views.sieve1, name ="sieve1"),
#    url(r'^(?P<article_key_id>[0-9]+)/(?P<article_sub_id>[0-9]+)/sieve2/$', views.sieve2, name ="sieve2"),
#    url(r'^(?P<article_key_id>[0-9]+)/begin2/$', views.begin2, name='begin2'),
    url(r'^quiz_1/$', views.quiz_1, name='quiz_1'),
    url(r'^quiz_2/$', views.quiz_2, name='quiz_2'),
    url(r'^quiz_3/$', views.quiz_3, name='quiz_3'),
    url(r'^quiz_4/$', views.quiz_4, name='quiz_4'),
    url(r'^quiz_5/$', views.quiz_5, name='quiz_5'),
    url(r'^not_pass/$', views.not_pass, name='not_pass'),
    url(r'^end_1/(?P<survey_code>[\w-]+)/$', views.end_1, name='end_1'),
    url(r'^end_2/(?P<survey_code>[\w-]+)/$', views.end_2, name='end_2'),
    url(r'^end_3/(?P<survey_code>[\w-]+)/$', views.end_3, name='end_3'),
    url(r'^end_4/(?P<survey_code>[\w-]+)/$', views.end_4, name='end_4'),
    url(r'^end_n5/(?P<survey_code>[\w-]+)/$', views.end_n5, name='end_n5'),
    url(r'^end_e5/(?P<survey_code>[\w-]+)/$', views.end_e5, name='end_e5'),
    url(r'^fetch_quiz/$', views.fetch_quiz, name='fetch_quiz'),
    url(r'^fetch_target_text/$', views.fetch_target_text, name='fetch_target_text'),
    url(r'^step1_info_Q_gen/$', views.step1_info_Q_gen, name='step1_info_Q_gen'),
    url(r'^gen_entities/$', views.gen_entities, name='gen_entities'),
    url(r'^fetch_q1/$', views.fetch_q1, name='fetch_q1'),
    url(r'^fetch_q1_all/$', views.fetch_q1_all, name='fetch_q1_all'),
    url(r'^fetch_q1_for_answer/$', views.fetch_q1_for_answer, name='fetch_q1_for_answer'),
    url(r'^step1_return/$', views.step1_return, name='step1_return'),
    url(r'^step2_return/$', views.step2_return, name='step2_return'),
    url(r'^step2_mid_return/$', views.step2_mid_return, name='step2_mid_return'),
    url(r'^step2_info_Q_ans/$', views.step2_info_Q_ans, name='step2_info_Q_ans'),
    url(r'^step3_causal_Q_gen/$', views.step3_causal_Q_gen, name='step3_causal_Q_gen'),
    url(r'^step4_causal_link/$', views.step4_causal_link, name='step4_causal_link'),
    url(r'^step5_causality_interpret_n/$', views.step5_causality_interpret_n, name='step5_causality_interpret_n'),
    url(r'^step5_causality_interpret_e/$', views.step5_causality_interpret_e, name='step5_causality_interpret_e'),
    url(r'^fetch_q_a_step3/$', views.fetch_q_a_step3, name='fetch_q_a_step3'),
    url(r'^fetch_prev_why_q_step3/$', views.fetch_prev_why_q_step3, name='fetch_prev_why_q_step3'),
    url(r'^step3_return/$', views.step3_return, name='step3_return'),
    url(r'^step4_return/$', views.step4_return, name='step4_return'),
    url(r'^step5_return/$', views.step5_return, name='step5_return'),
    url(r'^fetch_sub_text/$', views.fetch_sub_text, name='fetch_sub_text'),
    url(r'^fetch_causal_question/$', views.fetch_causal_question, name='fetch_causal_question'),
    url(r'^fetch_causal_question_step5/$', views.fetch_causal_question_step5, name='fetch_causal_question_step5'),
    url(r'^collect_reaction/', views.collect_reaction, name='collect_reaction'),
]
