# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 7, 50, 35, 246520)),
        ),
    ]
