# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0003_auto_20170818_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entities',
            new_name='Entity',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 9, 19, 49, 992944)),
        ),
    ]
