# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0004_auto_20170818_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 10, 53, 53, 48095, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='causalnode',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Article'),
        ),
    ]
