# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0006_auto_20170818_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(default='', max_length=200)),
                ('item_num', models.IntegerField(default='0')),
                ('status', models.IntegerField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 7, 41, 0, 917836, tzinfo=utc)),
        ),
    ]
