# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0007_auto_20170819_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal_num', models.IntegerField(default=0)),
                ('related_num', models.IntegerField(default=0)),
                ('not_related_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 8, 34, 9, 261160, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='link',
            name='end_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Article'),
        ),
        migrations.AddField(
            model_name='link',
            name='start_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.CausalNode'),
        ),
    ]
