# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0010_auto_20170821_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 11, 6, 49, 946806, tzinfo=utc)),
        ),
    ]
