# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0014_auto_20170822_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='labeling_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 2, 3, 38, 656135, tzinfo=utc)),
        ),
    ]
