# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0016_auto_20170822_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 2, 41, 6, 778652, tzinfo=utc)),
        ),
    ]
