# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0018_auto_20170822_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 4, 57, 29, 30020, tzinfo=utc)),
        ),
    ]
