# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0019_auto_20170822_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='unqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 6, 50, 33, 515306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
