# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0020_auto_20170822_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='causalnode',
            name='node_id',
            field=models.IntegerField(db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='causalnode',
            name='num_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 12, 47, 48, 52566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='link',
            name='labeling_stage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='unqualified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
