# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0021_auto_20170822_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_Workset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LW_id', models.IntegerField(db_index=True, default='0')),
                ('links', models.ManyToManyField(to='crowdsourcer.Link')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 12, 59, 48, 283690, tzinfo=utc)),
        ),
    ]
