# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0022_auto_20170822_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 2, 24, 58, 462007, tzinfo=utc)),
        ),
    ]
