# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0023_auto_20170823_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link_workset',
            old_name='LW_id',
            new_name='link_workset_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 2, 26, 36, 177137, tzinfo=utc)),
        ),
    ]
