# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0026_auto_20170823_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='endfirst',
        ),
        migrations.RemoveField(
            model_name='link',
            name='notsure',
        ),
        migrations.RemoveField(
            model_name='link',
            name='startfirst',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 12, 36, 41, 858167, tzinfo=utc)),
        ),
    ]
