# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0028_auto_20170823_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence_FT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_R', models.IntegerField(default=0)),
                ('ev_N', models.IntegerField(default=0)),
                ('FT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Full_text')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence_Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_R', models.IntegerField(default=0)),
                ('ev_N', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='causalnode',
            name='article',
        ),
        migrations.RemoveField(
            model_name='link',
            name='end_article',
        ),
        migrations.RemoveField(
            model_name='link',
            name='start_article',
        ),
        migrations.RemoveField(
            model_name='link_workset',
            name='links',
        ),
        migrations.DeleteModel(
            name='PilotData',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='Article_done',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='Link_done',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='article',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='FT_annot_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='FT_annot_R',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='art_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='interpret_annot_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='interpret_annot_R',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='key_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sum_annot_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sum_annot_R',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='title_annot_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='title_annot_R',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.date(2017, 8, 24)),
        ),
        migrations.DeleteModel(
            name='CausalNode',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Link_Workset',
        ),
        migrations.DeleteModel(
            name='Session_Info',
        ),
        migrations.AddField(
            model_name='summary',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Article'),
        ),
        migrations.AddField(
            model_name='sentence_sum',
            name='Sum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Summary'),
        ),
        migrations.AddField(
            model_name='full_text',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Article'),
        ),
    ]
