# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0029_auto_20170824_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art_id',
            new_name='sub_id',
        ),
        migrations.AddField(
            model_name='sentence_ft',
            name='sen',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sentence_sum',
            name='sen',
            field=models.TextField(default='', max_length=200),
        ),
    ]
