# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0030_auto_20170824_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence_ft',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence_sum',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='full_text',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Article'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Article'),
        ),
    ]
