# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0031_auto_20170824_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence_sum',
            name='Sum',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='art',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sum_annot_N',
            new_name='init_annot_N',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sum_annot_R',
            new_name='init_annot_R',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_key',
        ),
        migrations.RemoveField(
            model_name='article',
            name='key_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_annot_N',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_annot_R',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(default=datetime.date(2017, 8, 27)),
        ),
        migrations.DeleteModel(
            name='Sentence_Sum',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
