# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0032_auto_20170827_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deceptive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
