# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0034_auto_20170828_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=-1)),
                ('art_id', models.IntegerField(default=-1)),
                ('is_R', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('tag', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(default=0)),
                ('session_num', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Worker'),
        ),
    ]
