# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0035_auto_20170828_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1_id', models.IntegerField(default=0)),
                ('answer', models.TextField(default='', max_length=200)),
                ('num_vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer1_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1G_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(default=0)),
                ('choice', models.TextField(default='', max_length=200)),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.IntegerField(default=0)),
                ('interpretation', models.TextField(default='', max_length=200)),
                ('made_by_expert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_step_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_step_q_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='', max_length=200)),
                ('num_vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question1_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1G_id', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q2_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='', max_length=200)),
                ('num_vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question2_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q2G_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Target_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('season', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=0)),
                ('time_description', models.CharField(default='', max_length=200)),
                ('summary', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='full_text',
            name='art',
        ),
        migrations.RemoveField(
            model_name='sentence_ft',
            name='FT',
        ),
        migrations.RemoveField(
            model_name='work',
            name='worker',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='control_annot_N',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='control_annot_R',
            new_name='season',
        ),
        migrations.RemoveField(
            model_name='article',
            name='init_annot_N',
        ),
        migrations.RemoveField(
            model_name='article',
            name='init_annot_R',
        ),
        migrations.RemoveField(
            model_name='article',
            name='interpret_annot_N',
        ),
        migrations.RemoveField(
            model_name='article',
            name='interpret_annot_R',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_deceptive',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='time_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Full_text',
        ),
        migrations.DeleteModel(
            name='Sentence_FT',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='question2_group',
            name='related_articles',
            field=models.ManyToManyField(to='crowdsourcer.Article'),
        ),
        migrations.AddField(
            model_name='question2',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question2_group'),
        ),
        migrations.AddField(
            model_name='question1',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question1_group'),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='question2_g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question2_group'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcer.Pre_step_Q'),
        ),
        migrations.AddField(
            model_name='answer1_group',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question1_group'),
        ),
        migrations.AddField(
            model_name='answer1',
            name='answer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Answer1_group'),
        ),
    ]
