# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0037_auto_20170831_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
