# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0038_entity_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer1',
            name='answer_group',
        ),
        migrations.AddField(
            model_name='answer1',
            name='question_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question1_group'),
        ),
    ]
