# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0039_auto_20170901_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='article',
            name='season',
        ),
        migrations.RemoveField(
            model_name='article',
            name='time_description',
        ),
    ]
