# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0040_auto_20170903_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q2_Art_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vote', models.IntegerField(default=0)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='question2_group',
            name='related_articles',
        ),
        migrations.AddField(
            model_name='q2_art_link',
            name='Q2G',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdsourcer.Question2_group'),
        ),
    ]
