# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0041_auto_20170903_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='After_task_QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.IntegerField(default=0)),
                ('answer', models.TextField(default='', max_length=1000)),
                ('step', models.IntegerField(default=0)),
                ('expert', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='answer1',
            name='answer',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='interpretation',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question1',
            name='question',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question2',
            name='question',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='target_article',
            name='summary',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
