# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0042_auto_20170904_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question1_group',
            name='entity',
        ),
        migrations.AddField(
            model_name='question1_group',
            name='entity',
            field=models.ManyToManyField(to='crowdsourcer.Entity'),
        ),
    ]
