# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0043_auto_20170904_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer1',
            old_name='num_vote',
            new_name='num_vote_A',
        ),
    ]
