# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0044_auto_20170905_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='after_task_qa',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='answer1',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='q2_art_link',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question1',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question2',
            name='worker_code',
            field=models.TextField(default='', max_length=200),
        ),
    ]
