# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcer', '0046_answer1_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_Fail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('_pass', models.IntegerField(default=0)),
                ('_fail', models.IntegerField(default=0)),
                ('_tot', models.IntegerField(default=0)),
            ],
        ),
    ]
